# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.wcms::need.form_name

# Model Form Field configuration
form: $/waka/wcms/models/need/fields.yaml

# Model Class name
modelClass: Waka\Wcms\Models\Need

# Default redirect location
defaultRedirect: waka/wcms/needs

# Create page
create:
    title: waka.wcms::need.create
    redirect: waka/wcms/needs/update/:id
    redirectClose: waka/wcms/needs
    form: $/waka/wcms/models/need/fields_create.yaml

# Update page
update:
    title: waka.wcms::need.update
    redirect: waka/wcms/needs/update/:id
    redirectClose: waka/wcms/needs

# Preview page
preview:
    title: waka.wcms::need.preview_name
