# ===================================
#  Reorder Behavior Config
# ===================================

# Reorder Title
title: Reorder needs

# Attribute name
nameFrom: name

# Model Class name
modelClass: Waka\Wcms\Models\Need

# Toolbar widget configuration
#toolbar:
    # Partial for toolbar buttons
    # buttons: reorder_toolbar