# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: waka.wcms::solution.form_name

# Model Form Field configuration
form: $/waka/wcms/models/solution/fields.yaml

# Model Class name
modelClass: Waka\Wcms\Models\Solution

# Default redirect location
defaultRedirect: waka/wcms/solutions

# Create page
create:
    title: waka.wcms::solution.create
    redirect: waka/wcms/solutions/update/:id
    redirectClose: waka/wcms/solutions
    form: $/waka/wcms/models/solution/fields_create.yaml

# Update page
update:
    title: waka.wcms::solution.update
    redirect: waka/wcms/solutions/update/:id
    redirectClose: waka/wcms/solutions

# Preview page
preview:
    title: waka.wcms::solution.preview_name
